### ISSUE TITLE
WSL installation only exposes javascript and typescript language identifiers

### ISSUE THREAD

**Issue by ebednarz** [svipas/vscode-control-snippets#1]
Great extension, thank you so much. One thing that doesn't work well for me is WSL installation, though, where only the `javascript` and `typescript` language identifiers are exposed. Any idea?

(When I use the extension without WSL, I get the complete list.)

<img width="554" alt="wsl-control-snippets" src="https://user-images.githubusercontent.com/1093381/62855361-53782100-bcf2-11e9-8094-dd3efc04835d.png">

**Comment by svipas** [comment]
Hi, while you're using WSL extension you're remotely connected to other machine? Or you just installed WSL extension and you can't see complete list of extensions?

**Comment by ebednarz** [comment]
The extension is called "Remote - WSL"  (there are also SSH and Docker variants under the "Remote" umbrella), but there's no other machine involved. :)

So "Remote - WSL" is my only "local" extension, everything else is installed on the machine's WSL.

WSL: Ubuntu-18.04
VS Code 1.37.0
Windows 10 Home, version 1903

**Comment by svipas** [comment]
I tried to install WSL and opened Control Snippets and everything was OK. So I assume you're connected to the remote machine via WSL extension. I will try to take a look into this issue by testing it by myself by connecting to remote container or machine.

**EDIT:** I just tested by myself and I see the same issue. I will try to fix it.

**Comment by svipas** [comment]
It works as supposed to work you're seeing only `javascript` and `typescript` because only these extensions contains snippets and only they are enabled in remote machine.

I will update documentation to explain it.

**Take a look at this screenshot:**

<img width="1440" alt="Screen Shot 2019-08-13 at 00 24 05" src="https://user-images.githubusercontent.com/10441177/62899634-e5b70e00-bd60-11e9-92fb-56faae421955.png">

As you can see I have rust installed so I can control snippets, I don't see complete list because it doesn't contain for e.g. php or c extensions that's why after disconnecting from remote machine you're seeing way more extensions in the Control Snippets. VS Code in remote machine disables a lot of extensions, just open the `Extensions: Show Built-in Extensions` and search for `@builtin` you will see for e.g. php, cpp, bat, etc. extensions are disabled.

**Comment by ebednarz** [comment]
Thanks for the explanation :)

(That's a container, not WSL, right? But that shouldn't matter for the outcome, indeed.)

**Comment by svipas** [comment]
Updated README and added emoji to separate local and remote extensions :)
